name: Build Release

on:
    # This will trigger when a tag like v1.0.0 is pushed
    # will create a release
    push:
        tags:
            - "*.*.*"
    # Manual trigger for creating an artifact (button in the UI)
    workflow_dispatch:

permissions:
    packages: write
    contents: write

jobs:
    build-windows:
        runs-on: windows-latest
        steps:
            - uses: actions/checkout@v4

            # Setup Rust
            - name: install Rust stable
              uses: dtolnay/rust-toolchain@stable

            # Compile the binary
            - name: Build with ${{ matrix.target }}
              run: cross build --release

            # Copy built binary to output directory
            - name: Copy binary to output
              run: cp target/release/AnselSDK64.dll AnselSDK64.dll
              shell: bash

            # Upload the built artifact
            - name: Upload artifact
              uses: actions/upload-artifact@v4
              with:
                  name: AnselSDK64.dll
                  path: AnselSDK64.dll

    release:
        name: Create Release
        runs-on: ubuntu-latest
        needs: [build-windows]

        steps:
            # Checkout the repo
            - uses: actions/checkout@v4

            # Download all the compiled artifacts from previous
            # steps
            - name: Download all build artifacts
              uses: actions/download-artifact@v4
              with:
                  path: dist
                  merge-multiple: true

            # Create the github release if we pushed up a new tag
            - name: Create GitHub Release
              uses: softprops/action-gh-release@v2
              if: github.event_name == 'push'
              with:
                  tag_name: ${{ github.ref_name }}
                  name: v${{ github.ref_name }}
                  draft: true
                  files: dist/*
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
